# Generated by Django 5.2.9 on 2025-12-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chatthread_message_chat_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('generate', 'Generare imediata'), ('workflow', 'Trimitere pe flux')], default='generate', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word (.doc pe baza de HTML)')], default='pdf', max_length=10)),
                ('dynamic_values', models.JSONField(blank=True, default=dict)),
                ('rendered_html', models.TextField(blank=True)),
                ('signature', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'In lucru'), ('in_progress', 'In editare'), ('completed', 'Finalizat')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='core.citizen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items_created', to=settings.AUTH_USER_MODEL)),
                ('final_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='core.generateddocument')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='core.municipality')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='core.documenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
