# Generated by Django 5.2.9 on 2025-12-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_documenttemplate_template_type_workitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signature_images/'),
        ),
    ]
