# Generated by Django 5.2.9 on 2025-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_workitem_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFieldLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('length', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
